language: ruby
rvm:
 - "2.2.1"
notifications:
  email: false
before_script:
  - psql -c "CREATE USER conjugeur;" -U postgres
  - psql -c "CREATE DATABASE conjugeur_test;" -U postgres
  - rake db:create RAILS_ENV=test
  - rake db:migrate RAILS_ENV=test
script: bundle exec rspec spec
